"""
E10: PCA Dimensionality Reduction
Flattens the 768-D soft-prompt generated by the 3 architectures into a 2-D scatter graph 
to map topological clustering generalizations.
"""
import subprocess
from pathlib import Path
import json
import torch
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA

PYTHON = r".\.venv\Scripts\python.exe"
import sys; sys.path.append(r"c:\Users\beyon\quantum-prompt-optimizer\src")
from training.trainer import TrainConfig
from models.quantum_agent import HighCapacityQuantumAgent
from models.classical_agent import ClassicalDavidAgent, ClassicalGoliathAgent

tasks = [
    {"name": "glue", "config": "sst2", "batch": "8"},
    {"name": "glue", "config": "rte", "batch": "8"},
    {"name": "super_glue", "config": "boolq", "batch": "2"},
    {"name": "ag_news", "config": "default", "batch": "8"}
]

print("==========================================")
print("E10: Stage 1 - Parameter Verification (Seeds 0-9)")
print("==========================================")

base_dir = Path(r"c:\Users\beyon\quantum-prompt-optimizer\experiments\gpt2")
seeds = list(range(10))

for t in tasks:
    for seed in seeds:
        tgt_folder = base_dir / t["config"] / f"seed{seed}_ep5_full"
        if tgt_folder.exists() and list(tgt_folder.glob("*.pt")):
            continue
            
        print(f"[!] Missing Checkpoint [{t['config']} | Seed {seed}]. Rebuilding...")
        cmd = [
            PYTHON, "-u", "train.py",
            "--dataset-name", t["name"],
            "--dataset-config", t["config"],
            "--epochs", "5",
            "--seed", str(seed),
            "--n-qubits", "8",
            "--n-layers", "30",
            "--batch-size", t["batch"],
            "--checkpoint-every", "5",
            "--print-every", "1"
        ]
        subprocess.run(cmd, check=True)

print("==========================================")
print("E10: Stage 2 - 768-D Extract & Compress")
print("==========================================")

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
dummy_input = torch.zeros(8).to(device)

def get_agents():
    # Initialize blank models
    q_agent = HighCapacityQuantumAgent(n_qubits=8, n_layers=30, embed_dim=768).to(device)
    _ = q_agent() # Pre-init Pennylane layer
    q_total = sum(p.numel() for p in q_agent.parameters() if p.requires_grad)
    
    d_agent = ClassicalDavidAgent(n_inputs=8, embed_dim=768, exact_params=q_total).to(device)
    c_agent = ClassicalGoliathAgent(n_inputs=8, embed_dim=768).to(device)
    return q_agent, d_agent, c_agent

q_agent, d_agent, c_agent = get_agents()

q_vectors = []
d_vectors = []
c_vectors = []
vector_labels = [] # Task string mapping

for t in tasks:
    config_dir = base_dir / t["config"]
    for seed in seeds:
        seed_dir = config_dir / f"seed{seed}_ep5_full"
        ckpts = list(seed_dir.glob("ckpt_epoch_*.pt"))
        if not ckpts: continue
        ckpts.sort()
        ckpt_path = ckpts[-1]
        
        ckpt = torch.load(ckpt_path, map_location=device, weights_only=False)
        q_agent.load_state_dict(ckpt["quantum_state"])
        d_agent.load_state_dict(ckpt["david_state"])
        c_agent.load_state_dict(ckpt["classical_state"])
        
        with torch.no_grad():
            q_vec = q_agent().cpu().numpy()
            d_vec = d_agent(dummy_input).cpu().numpy()
            c_vec = c_agent(dummy_input).cpu().numpy()
            
        q_vectors.append(q_vec)
        d_vectors.append(d_vec)
        c_vectors.append(c_vec)
        vector_labels.append(t["config"])

q_vectors = np.vstack(q_vectors)
d_vectors = np.vstack(d_vectors)
c_vectors = np.vstack(c_vectors)
labels = np.array(vector_labels)

print("Compressing dimensions via PCA...")
pca_q = PCA(n_components=2).fit_transform(q_vectors)
pca_d = PCA(n_components=2).fit_transform(d_vectors)
pca_c = PCA(n_components=2).fit_transform(c_vectors)

print("==========================================")
print("E10: Stage 3 - Visual Sub-Cluster Rendering")
print("==========================================")

plot_dir = base_dir / "e10_plots"
plot_dir.mkdir(parents=True, exist_ok=True)

sns.set_theme(style="whitegrid")
unique_tasks = list(set(labels))
colors = sns.color_palette("Set1", len(unique_tasks))

def plot_scatter(pca_matrix, title, fname):
    plt.figure(figsize=(7, 6))
    for i, t in enumerate(unique_tasks):
        mask = labels == t
        plt.scatter(pca_matrix[mask, 0], pca_matrix[mask, 1], label=t, c=[colors[i]], s=100, alpha=0.8, edgecolors='white')
    plt.title(title, fontsize=14, fontweight='bold')
    plt.xlabel("Principal Component 1")
    plt.ylabel("Principal Component 2")
    plt.legend(title="Data Class", bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    plt.savefig(plot_dir / fname, dpi=150)
    plt.close()

plot_scatter(pca_q, "Quantum Agent: 768-D Prompt Sub-Clustering", "e10_pca_quantum.png")
plot_scatter(pca_d, "Classical David: 768-D Prompt Sub-Clustering", "e10_pca_david.png")
plot_scatter(pca_c, "Classical Goliath: 768-D Prompt Sub-Clustering", "e10_pca_goliath.png")

print(f"E10 Success! PCA maps securely exported to {str(plot_dir)}")
